# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cserv1_a/soc_ug/ed18src/Desktop/CStuff/ed18src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cserv1_a/soc_ug/ed18src/Desktop/CStuff/ed18src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cserv1_a/soc_ug/ed18src/Desktop/CStuff/ed18src/CMakeFiles /home/cserv1_a/soc_ug/ed18src/Desktop/CStuff/ed18src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cserv1_a/soc_ug/ed18src/Desktop/CStuff/ed18src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameOfLife

# Build rule for target.
GameOfLife: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GameOfLife
.PHONY : GameOfLife

# fast build rule for target.
GameOfLife/fast:
	$(MAKE) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/build
.PHONY : GameOfLife/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

display.o: display.c.o
.PHONY : display.o

# target to build an object file
display.c.o:
	$(MAKE) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/display.c.o
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/display.c.o
.PHONY : display.c.o

display.i: display.c.i
.PHONY : display.i

# target to preprocess a source file
display.c.i:
	$(MAKE) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/display.c.i
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/display.c.i
.PHONY : display.c.i

display.s: display.c.s
.PHONY : display.s

# target to generate assembly for a file
display.c.s:
	$(MAKE) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/display.c.s
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/display.c.s
.PHONY : display.c.s

game.o: game.c.o
.PHONY : game.o

# target to build an object file
game.c.o:
	$(MAKE) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/game.c.o
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/game.c.o
.PHONY : game.c.o

game.i: game.c.i
.PHONY : game.i

# target to preprocess a source file
game.c.i:
	$(MAKE) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/game.c.i
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/game.c.i
.PHONY : game.c.i

game.s: game.c.s
.PHONY : game.s

# target to generate assembly for a file
game.c.s:
	$(MAKE) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/game.c.s
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/game.c.s
.PHONY : game.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.c.s
.PHONY : main.c.s

unit_tests.o: unit_tests.c.o
.PHONY : unit_tests.o

# target to build an object file
unit_tests.c.o:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unit_tests.c.o
.PHONY : unit_tests.c.o

unit_tests.i: unit_tests.c.i
.PHONY : unit_tests.i

# target to preprocess a source file
unit_tests.c.i:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unit_tests.c.i
.PHONY : unit_tests.c.i

unit_tests.s: unit_tests.c.s
.PHONY : unit_tests.s

# target to generate assembly for a file
unit_tests.c.s:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unit_tests.c.s
.PHONY : unit_tests.c.s

unity/src/unity.o: unity/src/unity.c.o
.PHONY : unity/src/unity.o

# target to build an object file
unity/src/unity.c.o:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unity/src/unity.c.o
.PHONY : unity/src/unity.c.o

unity/src/unity.i: unity/src/unity.c.i
.PHONY : unity/src/unity.i

# target to preprocess a source file
unity/src/unity.c.i:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unity/src/unity.c.i
.PHONY : unity/src/unity.c.i

unity/src/unity.s: unity/src/unity.c.s
.PHONY : unity/src/unity.s

# target to generate assembly for a file
unity/src/unity.c.s:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unity/src/unity.c.s
.PHONY : unity/src/unity.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GameOfLife"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... unit_tests"
	@echo "... display.o"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... unit_tests.o"
	@echo "... unit_tests.i"
	@echo "... unit_tests.s"
	@echo "... unity/src/unity.o"
	@echo "... unity/src/unity.i"
	@echo "... unity/src/unity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

